import { builtinModules } from "node:module";
import path from "node:path";

import { defineConfig } from "vite";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
	...builtinModules.map((module) => `node:${module}`),
];

export default defineConfig(({ mode }) => ({
	resolve: {
		alias: {
			"@commands": path.resolve(__dirname, "src/commands"),
			"@config": path.resolve(__dirname, "src/internal-config.ts"),
			"@contracts": path.resolve(__dirname, "src/types"),
			"@data": path.resolve(__dirname, "src/data"),
			"@errors": path.resolve(__dirname, "src/errors"),
			"@filesystem": path.resolve(__dirname, "src/filesystem"),
			"@i18n": path.resolve(__dirname, "src/i18n"),
			"@provider": path.resolve(__dirname, "src/provider"),
			"@runtime": path.resolve(__dirname, "src/runtime"),
			"@sync": path.resolve(__dirname, "src/sync"),
			"@ui": path.resolve(__dirname, "src/ui"),
		},
	},
	build: {
		lib: {
			entry: "src/main.ts",
			formats: ["cjs"],
			fileName: () => "main.js",
		},
		rollupOptions: {
			external,
			output: {
				banner,
				exports: "default",
			},
		},
		outDir: "dist",
		emptyOutDir: false,
		sourcemap: mode !== "production",
		minify: mode === "production",
		target: "es2018",
	},
}));
