import { builtinModules } from "node:module";
import { defineConfig } from "vite";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
	...builtinModules.map((module) => `node:${module}`),
];

export default defineConfig(({ mode }) => ({
	build: {
		lib: {
			entry: "src/main.ts",
			formats: ["cjs"],
			fileName: () => "main.js",
		},
		rollupOptions: {
			external,
			output: {
				banner,
				exports: "default",
			},
		},
		outDir: ".",
		emptyOutDir: false,
		sourcemap: mode !== "production",
		minify: mode === "production",
		target: "es2018",
	},
}));
