import {
	createDriveSyncError,
	DriveSyncError,
	type DriveSyncErrorCode,
	type DriveSyncErrorInit,
	type DriveSyncErrorSummary,
	type DriveSyncErrorUserMessage,
	type ErrorCategory,
	type ErrorSeverity,
	formatDriveSyncErrorForLog,
	getDriveSyncErrorMessageForCode,
	getDriveSyncErrorUserMessage,
	getDriveSyncErrorUserMessageDescriptor,
	getRetryDelayForDriveSyncError,
	isAuthDriveSyncError,
	isAuthDriveSyncErrorCode,
	isDriveSyncError,
	isNotFoundDriveSyncError,
	isPathConflictDriveSyncError,
	isTransientNetworkDriveSyncError,
	normalizeUnknownDriveSyncError,
	shouldPauseAuthForError,
	shouldRetryBlockedDriveSyncError,
	shouldRetryBlockedDriveSyncErrorCode,
	toDriveSyncErrorSummary,
	translateDriveSyncErrorUserMessage,
} from "./drive-sync-error";

export {
	createDriveSyncError,
	DriveSyncError,
	formatDriveSyncErrorForLog,
	getDriveSyncErrorMessageForCode,
	getDriveSyncErrorUserMessage,
	getDriveSyncErrorUserMessageDescriptor,
	getRetryDelayForDriveSyncError,
	isAuthDriveSyncError,
	isAuthDriveSyncErrorCode,
	isDriveSyncError,
	isNotFoundDriveSyncError,
	isPathConflictDriveSyncError,
	isTransientNetworkDriveSyncError,
	normalizeUnknownDriveSyncError,
	shouldPauseAuthForError,
	shouldRetryBlockedDriveSyncError,
	shouldRetryBlockedDriveSyncErrorCode,
	toDriveSyncErrorSummary,
	translateDriveSyncErrorUserMessage,
};

export type {
	DriveSyncErrorCode,
	DriveSyncErrorInit,
	DriveSyncErrorSummary,
	DriveSyncErrorUserMessage,
	ErrorCategory,
	ErrorSeverity,
};
