export {
	createDriveSyncError,
	formatDriveSyncErrorForLog,
	getDriveSyncErrorUserMessage,
	getRetryDelayForDriveSyncError,
	isAuthDriveSyncError,
	isAuthDriveSyncErrorCode,
	isDriveSyncError,
	isNotFoundDriveSyncError,
	isPathConflictDriveSyncError,
	normalizeUnknownDriveSyncError,
	shouldPauseAuthForError,
	shouldRetryBlockedDriveSyncError,
	shouldRetryBlockedDriveSyncErrorCode,
	toDriveSyncErrorSummary,
	DriveSyncError,
	type DriveSyncErrorCode,
	type DriveSyncErrorInit,
	type DriveSyncErrorSummary,
	type ErrorCategory,
	type ErrorSeverity,
} from "./drive-sync-error";
