export const INTERNAL_MAX_CONCURRENT_JOBS = 2;
export const INTERNAL_MAX_RETRY_ATTEMPTS = 5;
export const INTERNAL_AUTO_SYNC_INTERVAL_MS = 300000;
export const INTERNAL_LOCAL_CHANGE_DEBOUNCE_MS = 800;
export const INTERNAL_NETWORK_POLICY_FAILURE_COOLDOWN_MS = 30000;
